import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { SearchBar } from '../components/SearchBar';
import { GlassCard } from '../components/GlassCard';
import { searchNaijpedia } from '../services/gemini';
import { SearchResult, LoadingState } from '../types';
import { MarkdownRenderer } from '../components/MarkdownRenderer';
import { Loader2, Zap, Link as LinkIcon, ArrowRight } from 'lucide-react';

export const SearchResults: React.FC = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const query = searchParams.get('q') || '';
  
  const [data, setData] = useState<SearchResult | null>(null);
  const [status, setStatus] = useState<LoadingState>(LoadingState.IDLE);

  useEffect(() => {
    if (!query) return;
    
    const performSearch = async () => {
      setStatus(LoadingState.LOADING);
      try {
        const result = await searchNaijpedia(query);
        setData(result);
        setStatus(LoadingState.SUCCESS);
      } catch (error) {
        setStatus(LoadingState.ERROR);
      }
    };

    performSearch();
  }, [query]);

  const handleSearch = (newQuery: string) => {
    setSearchParams({ q: newQuery });
  };

  return (
    <div className="min-h-screen w-full pt-28 pb-20 px-4 md:px-8 flex flex-col items-center relative">
       
      {/* Background */}
      <div className="fixed inset-0 overflow-hidden -z-10 pointer-events-none">
         <div className="absolute top-[-10%] right-[-10%] w-[60vw] h-[60vw] rounded-full bg-gradient-to-b from-gray-200/30 to-transparent dark:from-gray-800/20 dark:to-transparent blur-[120px] opacity-50" />
      </div>

      <div className="w-full max-w-4xl mb-12 animate-fade-in">
        <SearchBar onSearch={handleSearch} initialValue={query} />
      </div>

      <div className="w-full max-w-4xl flex-1 min-h-[50vh]">
        {status === LoadingState.LOADING && (
          <div className="space-y-6 animate-pulse">
             <div className="h-64 w-full rounded-2xl bg-white/40 dark:bg-white/5"></div>
             <div className="grid grid-cols-2 gap-4">
                <div className="h-24 rounded-2xl bg-white/40 dark:bg-white/5"></div>
                <div className="h-24 rounded-2xl bg-white/40 dark:bg-white/5"></div>
             </div>
          </div>
        )}

        {status === LoadingState.ERROR && (
           <GlassCard className="p-10 text-center">
             <div className="text-red-500 font-medium mb-2">Connection Error</div>
             <p className="text-gray-500">Please check your internet and try again.</p>
           </GlassCard>
        )}

        {status === LoadingState.SUCCESS && data && (
          <div className="space-y-8 animate-slide-up">
            
            {/* Main Answer Card */}
            <GlassCard className="p-8 md:p-10" hoverEffect={false}>
               <div className="flex items-center mb-8 border-b border-black/5 dark:border-white/5 pb-6">
                  <div className="w-10 h-10 rounded-full bg-black dark:bg-white flex items-center justify-center mr-4 shadow-lg">
                    <Zap size={20} className="text-white dark:text-black" fill="currentColor" />
                  </div>
                  <div>
                      <h1 className="text-2xl font-bold text-black dark:text-white tracking-tight">
                        Quick Answer
                      </h1>
                      <span className="text-xs font-medium text-gray-400 uppercase tracking-wider">Generated by Naijpedia AI</span>
                  </div>
               </div>
               
               <div className="prose prose-lg dark:prose-invert max-w-none">
                 <MarkdownRenderer content={data.text} />
               </div>
            </GlassCard>

            {/* Sources / Grounding */}
            {data.groundingChunks && data.groundingChunks.length > 0 && (
              <div>
                <div className="flex items-center justify-between mb-5 px-2">
                    <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest">
                    Verified Sources
                    </h3>
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {data.groundingChunks.map((chunk, idx) => {
                    if (!chunk.web) return null;
                    return (
                      <a 
                        key={idx} 
                        href={chunk.web.uri} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="block group h-full"
                      >
                        <GlassCard className="p-5 flex items-center h-full border-transparent hover:border-black/10 dark:hover:border-white/20">
                           <div className="w-10 h-10 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center mr-4 shrink-0 group-hover:bg-black group-hover:text-white dark:group-hover:bg-white dark:group-hover:text-black transition-colors">
                             <LinkIcon size={16} />
                           </div>
                           <div className="overflow-hidden flex-1">
                             <div className="text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-1">{new URL(chunk.web.uri).hostname}</div>
                             <div className="text-sm font-semibold text-black dark:text-white truncate group-hover:underline decoration-2 underline-offset-4">
                               {chunk.web.title}
                             </div>
                           </div>
                           <ArrowRight size={16} className="text-gray-300 dark:text-gray-600 group-hover:text-black dark:group-hover:text-white -translate-x-2 opacity-0 group-hover:opacity-100 group-hover:translate-x-0 transition-all" />
                        </GlassCard>
                      </a>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};